[package]
name = "hello-pyzurich"
version = "0.1.0"
authors = ["Martin Geisler <martin@geisler.net>"]

[dependencies]
hyper = "0.10.5"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
chrono = { version = "0.3", features = ["serde"] }
